### ISSUE TITLE
Combobox not keyboard accessible

### ISSUE THREAD

**Issue by terracoda** [phetsims/molarity#130] opened 2019-07-10 08:19 UTC
@twant, yesterday July 9th, the combobox was keyboard accessible, but today it is not. I can't move through the list of options with the arrow keys.

Please check, maybe related to changes made in #127 ?

**Comment by jessegreenberg** [comment] 2019-07-10 22:23
Sorry about that, this was caused by a change I made to scenery. I found this while looking into #126. Working again with the above commit, closing.

**Closed by jessegreenberg** 2019-07-10 22:23 UTC
Labels: dev:a11y, type:bug
