### ISSUE TITLE
The PhET-iO template crashes

### ISSUE THREAD

**Issue by samreid** [phetsims/molarity#49] opened 2018-08-18 04:53 UTC
Navigate to https://phet-io.colorado.edu/sims/molarity/1.4.1/ and download the "basic example of a functional wrapper" to a local file, then launch it in the browser.  I obtain this error and the sim doesn't launch:

> Assertion failed: Tandem was required but not supplied

When I changed `debug: true,` to `debug: false,`, then the simulation launched.  Discovered during https://github.com/phetsims/QA/issues/19

@zepumph are you available to investigate this?  I don't yet know if the problem is specific to Molarity or general.  I'll mark as high priority and meeting in case it is general.

**Comment by pixelzoom** [comment] 2018-08-18 16:07
@ariel-phet This is the second PhET-iO problem found in the recent Molarity 1.4 release.  (https://github.com/phetsims/phet-io-wrappers/issues/135 was the first.)  So it feels like we have a quality control problem wrt PhET-iO.  @samreid @zepumph Any thoughts on what the problem is? Are developers not spending enough time testing?  Are QA test instruction insufficient?

**Comment by samreid** [comment] 2018-08-19 00:00
I suspect the main problem is that it has been a long time since we have had a PhET-iO RC test, and PhET-iO has many new features.  We have been augmenting the instructions in https://github.com/phetsims/QA/issues/19 and should continue to do so.  I have notes in https://github.com/phetsims/phet-io-wrappers/issues/147 and https://github.com/phetsims/QA/issues/19#issuecomment-414032379 to update the PhET-iO testing documentation.

**Comment by zepumph** [comment] 2018-08-20 19:37
This is particularly hard to test because of https://github.com/phetsims/phet-io-wrappers/issues/145, I will try to get that to work first, then come back here.

**Comment by zepumph** [comment] 2018-08-20 23:01
This was a bit of a confusing chain to crack, let me document the steps I took to reproduce/diagnose and the problems along the way. 


First I noticed that the assertion that triggers in the debug version is less than helpful, since all the Type names are garbled. I think it would be good to add the Type name to that assertion error if we able (not sure how to manage that).

Next I found that when trying to test locally, recent changes moving the index wrapper caused a bug that I fixed in https://github.com/phetsims/phet-io-wrappers/issues/145.

Next, I was successfully able to checkout 1.4 shas and test locally, finding that the same error occurs in requirejs mode (i.e. this assertion fails when just launching the standalone version of the sim in requirejs).

The error was probably from taking a sun sha in the middle of the implementation of https://github.com/phetsims/sun/issues/340. This means that this issue is not systemic, and will just need a simply patch in sun (this commit will not need to be on master, just for molarity 1.4). 

On top of this, we should add https://github.com/phetsims/phet-io-wrappers/commit/f94aa36747ee94058ca7a29ae98c5470f2524017 so that we can easily test that the patch works as expects. 

Honestly I'm very surprised that this made it through testing, and perhaps we need a bit more strict testing (i.e. using the debug flag in our wrapper suite). That said, it is also pretty cool that such an assertion failed, yet all of our phet-io infrastructure was fault tolerant to it.

@pixelzoom since all of these changes are outside of molarity, I will plan to make the commit, and then pass it over to you for the maintenance release, unless you would like me to do the release.

**Comment by pixelzoom** [comment] 2018-08-20 23:05
Thanks @zepumph.  I can do the maintenance release.  Let me know when you're done.

**Comment by zepumph** [comment] 2018-08-20 23:35
I have fixed this problem for the molarity 1.4 branch. I did so by:

* checkout molarity 1.4
* checking out shas for branch
* `cd sun`
* `git checkout -b molarity-1.4`
* `git cherry-pick 4017a896c92862bd82baa3a02ca80e27c191ee22` (https://github.com/phetsims/sun/commit/4017a896c92862bd82baa3a02ca80e27c191ee22)

Still to do:
* I did not update the top level dependencies file at all.
* I did not branch/cherry-pick in phetsims/phet-io-wrappers@f94aa36 but would recommend doing so to make local testing easier.

Testing steps to make sure that the patch fixed things:
* Launch molarity wrapper index locally and open the "Simulation" link, for my server it is: `http://localhost/molarity/molarity_en.html?brand=phet-io&phetioStandalone&sim=molarity&ea`. The sim should load without error.
* (will require the phet-io-wrappers cherry-pick) Build the phet-io brand sim, and navigate to the index (`build/phet-io/`). Copy the "template" code into a new html file you create in the `molarity/build/phet-io/` folder. It should load without error, and when you open the About Dialog, no errors should occur.

@pixelzoom over to you to create the maintenance release. Please let me know how/if the steps above were sub-optimal and if so please provide feedback to how I can do this better next time. I know that you prefer doing maintenance releases for your sims, which is very understandable and reasonable. For this particular situation I feel like I'm leaving you in a half baked state. Let me know if I can help any more.

**Comment by pixelzoom** [comment] 2018-08-21 16:16
@zepumph I'm in the dark about this issue, and it looks like things are partially patched.  So how about if you complete and test all patches that are required for the molarity 1.4 branch and its dependencies.  When it's ready to go, assign back to me, and I'll publish the RC, create the GitHub issue, etc.

**Comment by zepumph** [comment] 2018-08-23 01:04
Marking high so it doesn't fall off my radar. It shouldn't take too long.

**Comment by zepumph** [comment] 2018-08-23 01:34
Here are the steps I just did:
* checkout molarity 1.4 and all dependencies
* create phet-io-wrappers branch "molarity-1.4"
* cherry pick in the above commit needed for local testing
* build the simulation for phet-io brand
* tested the fix by: (1) running the debug simulation in standalone, and (2) copying the wrapper template from the index into a newly created `build/phet-io/html.html` and running it. 
* I think copied the built dependencies into the top level file, and committed above. 

@pixelzoom over to you for final maintenance release, checkout-shas should now point you in the correct location, but just to make sure, it would be good to confirm that you are on the `molarity-1.4` branches of sun and phet-io-wrappers before completing the maintenance release.

**Comment by zepumph** [comment] 2018-08-23 01:35
(note) I apologize for the potentially superfluous lists of steps, but I'm not yet confident enough in the build process to proceed in a simpler manner.

**Comment by pixelzoom** [comment] 2018-08-23 15:49
@zepumph said:
> ... checkout-shas should now point you in the correct location, ...

FYI, according to @jonathanolson, we should be using `grunt checkout-target`, not `checkout-shas`.

**Comment by zepumph** [comment] 2018-08-23 17:49
Thank you! good to know. I can't seem to keep up with all the good code.

**Comment by pixelzoom** [comment] 2018-08-23 18:29
I did a local build:

```
cd molarity
grunt checkout-target --target=1.4
grunt --brands=phet,phet-io
```

The brand=phet version tested OK.

For the brand=phet-io version, here's @zepumph's test instructions with clarification:

> (1) running the debug simulation in standalone, 

Navigate to molarity/build/phet-io, click the "Simulation" link, replace the filename in the URL with "molarity_all_phet-io_debug.html".   So my URL is 
http://localhost/~cmalley/GitHub/molarity/build/phet-io/molarity_all_phet-io_debug.html?phetioStandalone.

> and (2) copying the wrapper template from the index into a newly created build/phet-io/html.html and running it.

Navigate to molarity/build/phet-io, copy the HTML that is shown in the black box in the API subsection, paste it into a new html file, run that html file. 

The above tests passed.

**Comment by pixelzoom** [comment] 2018-08-23 19:13
This is to be verified in 1.4.2.-rc.1 testing, see https://github.com/phetsims/QA/issues/178.  @KatieWoe you can use the test procedure that I've described in https://github.com/phetsims/molarity/issues/49#issuecomment-415521701.

**Comment by KatieWoe** [comment] 2018-08-23 19:25
Just tested on Win 10 chrome, and it seems to work.  Will test on other platforms before verifying in phetsims/QA#178

**Comment by KatieWoe** [comment] 2018-10-23 16:16
Confirmed 1.4.2-rc.1

**Comment by pixelzoom** [comment] 2018-10-31 23:08
Status? This has been high-priority since 8/17.

**Comment by samreid** [comment] 2018-11-01 01:38
According to https://github.com/phetsims/QA/issues/178#issuecomment-417726397 we deployed 1.4.2.  @pixelzoom can this issue be closed?

**Closed** 2018-11-01 16:09 UTC
Labels: dev:maintenance-release, dev:phet-io, priority:2-high, status:blocks-sim-publication
