### ISSUE TITLE
Title not translatable

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molarity#226] opened 2020-02-25 21:11 UTC
For https://github.com/phetsims/QA/issues/482
String tests show that the molarity title on the nav bar isn't translatable. It is in the published version.
![molaritynottranslated](https://user-images.githubusercontent.com/41024075/75288012-b174dd80-57d8-11ea-8560-54f50a3a679f.png)

**Comment by jonathanolson** [comment] 2020-02-25 21:34
This is something else where I believe it's fixed now.

Just updated a new version of molarity built with what I have in my working copy:

https://phet-dev.colorado.edu/molarity-modules-test/molarity_en_phet.html?stringTest=asrtlkn

I can confirm that it seems broken before, and working now. My suspicion is that removing the string workarounds for https://github.com/phetsims/chipper/issues/832 fixed it, since the "screen" title was one of the strings changed?

Can you confirm (and if so close) that the above link seems to work OK for that?

**Closed** 2020-02-25 21:36 UTC
Labels: type:i18n
