### ISSUE TITLE
Firefox 23 Android color change on the beaker

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/molarity#8] opened 2013-09-05 17:33 UTC
While the fluid is changing, it switches to a dark color. Then once it is done changing (slider drags are stopped), it switches back to the correct color.

![molarity-firefox-mobile-bug](https://f.cloud.github.com/assets/480878/1090126/2fff8a04-1651-11e3-8ac4-b4e47a2a69ca.png)

Tracking upstream in Scenery at https://github.com/phetsims/scenery/issues/125

**Comment by pixelzoom** [comment] 2015-05-26 16:54
@jonathanolson Was this resolved by scenery 0.2 ?

**Comment by pixelzoom** [comment] 2015-05-26 16:55
FYI, I don't see this issue on Mac OS 10.3.3 with FF 35.0.1.

**Comment by pixelzoom** [comment] 2015-05-26 16:56
FYI, I don't see this issue on Mac OS 10.3.3 with FF 35.0.1. Was this issue specific to Android? If so, why are we testing FF on Android, it's not a supported platform?

**Comment by jonathanolson** [comment] 2015-05-26 18:04
It was specific to Android, and I believe it was on the list at the time I did this testing?

**Comment by pixelzoom** [comment] 2015-05-26 18:15
@jonathanolson Is it still and issue, and do you think it needs to be addressed before "Summer 2015 redeploy"?

**Comment by jonathanolson** [comment] 2015-05-28 01:04
Definitely not something to address before the redeploy, since there's probably nothing we could do if it still is a bug. Don't have an Android charged at the moment, let me know if I should get one plugged in and test.

**Comment by pixelzoom** [comment] 2015-08-25 22:45
First step will be to see if this is still reproducible. It's been a long time (9/5/13) since it was reported.

**Comment by pixelzoom** [comment] 2015-08-30 19:48
Tested with 1.0.0-rc.2 (the version reported) and master, using Nexus 7 + Android 5.1.1 + FF 40.0. This problem is no longer reproducible, probably addressed by Mozilla in some release since FF 23.

Closing.

**Closed by pixelzoom** 2015-08-30 19:48 UTC
Labels: bug, Summer 2015 redeploy
