### ISSUE TITLE
Update Interactive Description Design Doc

### ISSUE THREAD

**Issue by emily-phet** [phetsims/molarity#227] opened 2020-03-02 20:37 UTC
This issue is in response to @terracoda adding this to remaining to-do's for the Molarity in today's postmortem. 

The goal for the design doc is that it documents the final design, it can also serve as an archive our documentation showing the design process. 

Ideally, when a sim is published, there top of the document shows the "design-complete" or "final" design of the sim, and below that may be older variations, design notes, interview notes, etc that were captured throughout the design process. 

For Molarity's design document, it's up to @terracoda and @Matthew-Moore240 what is needed. If you think just stripping out some extraneous or ultimately unused text from the current doc would serve as a reasonable documentation of the published design, please do that. 

If you find yourself stripping out things and wanting to hold on to them, please consider the following:
- copying the existing content to the top of the same document. Editing this new content at the top (stripping things out). Leave the existing design content untouched at the bottom of the doc. Just add a headings to indicate "Current Design" and "Design Notes" or something like that. 

Please avoid creating two docs (an older archived version and a new "cleaner" one) unless you think it will be unusable to have all the content in one doc.

**Comment by emily-phet** [comment] 2020-03-02 20:39
Let's aim to have this done by the end of the Q1 if at all possible. It would be ideal to not carry any Molarity tasks with us into Q2. @terracoda - let me know if this seems problematic with your other rocks. Hopefully @Matthew-Moore240 can support this significantly.

**Comment by terracoda** [comment] 2020-03-02 20:45
@emily-phet, you have pointed out a big difference in how the Main Sim design docs have worked and how I have used the Interactive Description design doc. 

In the Interactive Description Design doc, I have never organized from top to bottom by Design Meetings. But rather to outline a first draft of the different types of descriptions. Once implementation starts things can get really messy since ideation and design changes are all integrated into the original draft.

It might be good to discuss this a bit more. My strategy thus far is to make an archived copy of the design doc when I need to make big changes.

**Comment by terracoda** [comment] 2020-03-02 20:45
It shouldn't be a problem to get it done by end of quarter.

**Comment by emily-phet** [comment] 2020-03-02 21:10
@terracoda 
The design doc doesn't need to be organized by design meeting - i didn't intend to imply that above. 

I meant only that there is a "working document" - the stuff that gets messy throughout the design process with layered comments, edits, etc. Sometimes that ends up being organized at different time points, but often not. That's all ok. The doc should serve the needs of the design team at the time. 

Once a sim is design complete, though, it's helpful to have a place where a reasonably understandable representation of the final, published, design is reflected. Less messy. It's nice if that can be done at the top of the design doc - so anyone going there who is unfamiliar finds that first. Then the original more messy material is below. For someone not looking for that, they'll stop if they get there. But, it's still there for everyone who knowledgeable about that doc. 

So, I think I was just unclear in more original comment. I don't think there is a difference in how the Interaction Description design doc is used and what I was meaning above.

**Comment by terracoda** [comment] 2020-10-08 13:45
I have resolved all the open comments in the design doc.  I think the design doc is relatively clean. I am un-assigning myself from this issue.

**Comment by terracoda** [comment] 2020-10-08 15:06
I think it is safe to close this issue.
As design docs go, this one is pretty clean, it reflects some of the challenges we encountered as we designed the description.

**Closed by terracoda** 2020-10-08 15:06 UTC
