### ISSUE TITLE
iOS 11 returning to sim causes delay in input

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molarity#211] opened 2020-01-07 16:56 UTC
**Device**
Dalton
**OS**
iOS 11.4.1
**Browser**
Safari
**Problem Description**
For https://github.com/phetsims/QA/issues/464
If you go to a new tab (such as when you open a screenshot) and then return to the sim, there will be a few seconds where inputs are not registered. After a second or two the missed inputs will occur rapid fire and the sim will begin to behave normally. This didn't seem to happen in the published sim from what I could tell.
**Steps to reproduce**
1. Open a screenshot of the sim and stay there for several seconds
2. X out of the screenshot to return to the sim
3. Immediately begin clicking the show values checkbox as many times as you can
4. After a second or two the inputs will register

**Visuals**
![pauseincontrolgif](https://user-images.githubusercontent.com/41024075/71913039-d41d3b00-3133-11ea-9aa1-3288d5418c18.gif)

**Comment by KatieWoe** [comment] 2020-01-07 16:59
Also didn't seem to occur in iOS 12

**Comment by KatieWoe** [comment] 2020-01-07 17:23
Also seems to happen on a fresh load of the sim.

**Comment by jessegreenberg** [comment] 2020-01-15 19:18
Thanks @KatieWoe , very unlikely to be a sim issue and probably applies to many. I will try to reproduce.

**Comment by jessegreenberg** [comment] 2020-01-15 19:28
I am not able to make this happen on iOS 13.3.

**Comment by jessegreenberg** [comment] 2020-01-15 19:55
OK I can see this happening on iOS 11. While input is delayed the entire sim looks fuzzy, like a lower quality image of the simulation. And I think  that is exactly what it is, Safari is showing a cached image of the sim saved when tabs were switched. This also happens on other web pages not related to PhET - I see similar pixelation before the page becomes clear, though it only lasts for half a second. For latest version of molarity it lasts 0 - 2 seconds. For published Molarity it is definitely shorter,  maybe 0-1 seconds.

**Comment by jessegreenberg** [comment] 2020-01-15 20:04
I am not seeing this happen for other sims like diffusion or balloons-and-static-electricity.

Also, now that I have ~7 tabs open (a few sims, a few random web pages) I am not seeing this happen at all anymore on iOS 11. This just feels like a Safari optimization to make the open web pages faster. I am not sure why in some cases it occurs and others it doesn't or why there seems to be ~1 second more delay on molarity master some times.

**Comment by jessegreenberg** [comment] 2020-01-15 20:08
@ariel-phet can you please take a look at this issue and https://github.com/phetsims/molarity/issues/211#issuecomment-574833431? Does this issue need to block publication of molarity? Does this issue require further work (probably in scenery somewhere)?

**Comment by ariel-phet** [comment] 2020-01-15 20:15
@jessegreenberg @KatieWoe considering that the sim returns to normal fairly quickly, and this is an older iOS, I am not particularly concerned.

Looking at this website, https://david-smith.org/iosversionstats/, it appears iOS 11 is down to about 1% (we should have Oliver check into usage stats, and we might consider dropping support in the near future). Marking as `wontfix`

**Closed** 2020-01-15 20:15 UTC
Labels: type:bug, type:wontfix
